trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: 'Build'
  jobs:
    - job: build
      displayName: 'Build'
      pool:
        vmImage: ubuntu-latest
      steps:
        # - task: npmAuthenticate@0
        # inputs:
        #   workingFile: '.npmrc'
        #   customEndpoint: 'id-commons-registry'
        # displayName: 'Npm: login'
        - script: "npm ci"
          displayName: 'Npm: install'
        - script: "npm run build"
          displayName: 'Npm: build'

- stage: Test
  displayName: Test
  jobs:
    - job: test
      displayName: 'Test: Sonar'
      pool:
        demands: npm  
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'equipoinnovaciondigital'
          scannerMode: 'CLI'
          configFile: devops/sonar-project.properties
        displayName: 'Sonar: Prepare'
      - task: Npm@1
        inputs:
          command: 'ci'
          workingDir: '.'
        displayName: 'Npm: ci'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: run test:cov
        displayName: 'Npm: test'
      - task: SonarCloudAnalyze@1
        displayName: 'Sonar: Analyze'
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'
        displayName: 'Sonar: Publish'
      # - task: sonarcloud-buildbreaker@2
      #   inputs:
      #     SonarCloud: 'SonarCloud'
      #     organization: 'equipoinnovaciondigital'
      #   displayName: 'Sonar: Validation Status Sonar'

- stage: Artifact
  displayName: 'Artifact'
  jobs:
    - job: artifact
      displayName: 'Artifact: ubuntu'
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: CopyFiles@2
          inputs:
            Contents: '**'
            targetFolder: '$(Build.ArtifactStagingDirectory)'    
          displayName: 'Artifact: Copy'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: 'Artifact: Publish'