trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  displayName: Test
  jobs:
    - job: test
      displayName: 'Test: Sonar'
      pool:
        demands: npm  
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'equipoinnovaciondigital'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'EquipoInnovacionDigital_bcs-mortgage-frontend'
          cliProjectName: 'bcs-mortgage-frontend'
          cliSources: '.'
          extraProperties: |
            sonar.sources=.
            sonar.javascript.lcov.reportPaths=coverage/lcov.info
            Dsonar.testExecutionReportPaths=test-report.xml
        displayName: 'Sonar: Prepare'
      - task: Npm@1
        inputs:
          command: 'ci'
          workingDir: '.'
        displayName: 'Npm: ci'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: run test:cov
        displayName: 'Npm: test'
      - task: SonarCloudAnalyze@1
        displayName: 'Sonar: Analyze'
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'
        displayName: 'Sonar: Publish'
      - task: sonarcloud-buildbreaker@2
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'equipoinnovaciondigital'
        displayName: 'Sonar: Validation Status Sonar'

- stage: Artifact
  displayName: 'Artifact'
  jobs:
    - job: artifact
      displayName: 'Artifact: ubuntu'
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: CopyFiles@2
          inputs:
            Contents: '**'
            targetFolder: '$(Build.ArtifactStagingDirectory)'    
          displayName: 'Artifact: Copy'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          displayName: 'Artifact: Publish'