trigger:
- pull_request

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  displayName: Test
  jobs:
    - job: test
      displayName: 'Test: Sonar'
      pool:
        demands: npm  
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'equipoinnovaciondigital'
          scannerMode: 'CLI'
          configMode: 'file'
        displayName: 'Sonar: Prepare'
      - task: Npm@1
        inputs:
          command: 'ci'
          workingDir: '.'
        displayName: 'Npm: ci'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: run test:cov
        displayName: 'Npm: test'
      - task: SonarCloudAnalyze@1
        displayName: 'Sonar: Analyze'
#      - task: SonarCloudPublish@1
#        inputs:
#          pollingTimeoutSec: '300'
#        displayName: 'Sonar: Publish'
#      - task: sonarcloud-buildbreaker@2
#        inputs:
#          SonarCloud: 'SonarCloud'
#          organization: 'equipoinnovaciondigital'
#        displayName: 'Sonar: Validation Status Sonar'