export const routes = {
  home: '/',
  startProccess: '/inicio-solicitud',
  ratings: '/calificacion-solicitud',
  otp: '/validacion-otp',
  otc: '/validacion-otc',
  validacionIdentidad: '/validacion-identidad',
  validacionBiometrica: '/validacion-biometrica',
  validacionErrorValidacionIdentidad: '/validacion/error-validacionIdentidad',
  validacionErrorPreguntas: 'validacion/error-validacion-identidad-preguntas',
  validacionErrorIntentos: 'validacion/error-numero-intentos',
  validacionErrorBloqueo: 'validacion/error-bloqueo',
  errorValidacion: '/validacion/error-validacion/',
  validacionErrorDiario: '/validacion/error-validacionDiario/',
  validacionBlock: '/validacion/error-validacionBlock/',
  errorCreditBankApplication: '/validacion/rechazo-solicitud',
  inactivityScreen: '/inactividad',
  simulador: '/simulador',
  simuladorResumen: '/simulador/resumen',
  consultancy: '/asesoria',
  onboarding: '/bienvenida',
  authentication: '/autenticacion',
  personalData: '/datos-personales',
  sarlaft: '/preguntas-sarlaft',
  finalcialData: '/datos-financieros',
  creditData: '/datos-credito',
  summaryApprovalPage: '/',
  approvalDataPage: '/confirmacion-solicitud',
  ResumenSolicitud: '/resumen-solicitud',
  servicError: '/validacion/error-servicio',
  validacionSucursalError: '/validacion/error-validacionSucursal',
  validacionError: '/validacion/error'

};
