---
apiVersion: v1
data:
  APIURL: {{ .Values.REDISKEY | toString | b64enc | quote }}
  KYCAPIURL: {{ .Values.REDISURL | toString | b64enc | quote }}
  KEYKYCHASH: {{ .Values.REDISPORT | toString | b64enc | quote }}
  KEYSESSIONSTORAGE: {{ .Values.REDISPORT | toString | b64enc | quote }}
kind: Secret
metadata:
  name: "{{ .Values.application_name }}-{{ .Values.enviroment_name }}"
  namespace: "{{ .Values.namespace_name }}"
type: Opaque
