---
apiVersion: v1
data:
  KEYENCRYPTADIGITAL: {{ .Values.KEYENCRYPTADIGITAL | toString | b64enc | quote }}
  KEYSESSIONSTORAGE: {{ .Values.KEYSESSIONSTORAGE | toString | b64enc | quote }}
  TAGMANAGER: {{ .Values.TAGMANAGER | toString | b64enc | quote }}
  APIURLMORTGAGE: {{ .Values.APIURLMORTGAGE | toString | b64enc | quote }}
kind: Secret
metadata:
  name: "{{ .Values.application_name }}-{{ .Values.enviroment_name }}"
  namespace: "{{ .Values.namespace_name }}"
type: Opaque
