apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.application_name }}-{{ .Values.enviroment_name }}"
  namespace: "{{ .Values.namespace_name }}"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.container_port }}
  selector:
    app: "{{ .Values.application_name }}-{{ .Values.enviroment_name }}"