import Head from 'next/head';
import Link from 'next/link';
import { routes } from '../routes';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={routes.startProccess}>Inicio de soliciutd</Link>
      <br />
      <Link href={routes.ratings}>Calificacion de solicitud</Link>
      <br />
      <Link href={routes.otp}>Validacion otp</Link>
    </div>
  );
}
